//==========================================================================
//  alu_tb.v  -  self-checking testbench for the ALU
//
//  Do not edit this file. It is the specification of what alu.v must do.
//  Run it, read the failures, fix alu.v, run it again.
//
//  Vivado : Add Sources -> simulation sources -> alu_tb.v, set as top,
//           Run Simulation -> Run Behavioral Simulation, read the Tcl console.
//  Icarus : iverilog -I rtl -o alu_tb.out rtl/alu.v tb/alu_tb.v && vvp alu_tb.out
//==========================================================================
`timescale 1ns / 1ps
`include "defines.vh"

module alu_tb;

    reg  [31:0] a, b;
    reg  [3:0]  ctrl;
    wire [31:0] result;
    wire        zero;

    integer passed = 0;
    integer failed = 0;

    alu dut (.a(a), .b(b), .alu_ctrl(ctrl), .result(result), .zero(zero));

    // apply one vector and compare against the expected result
    task check;
        input [8*18:1] name;
        input [3:0]    c;
        input [31:0]   va, vb, expected;
        begin
            a = va; b = vb; ctrl = c;
            #1;
            if (result === expected) begin
                passed = passed + 1;
            end else begin
                failed = failed + 1;
                $display("  FAIL  %0s  a=%08h b=%08h  got %08h  want %08h",
                         name, va, vb, result, expected);
            end
        end
    endtask

    task check_zero;
        input [8*18:1] name;
        input          expected;
        begin
            #1;
            if (zero === expected) begin
                passed = passed + 1;
            end else begin
                failed = failed + 1;
                $display("  FAIL  %0s  zero flag got %b  want %b", name, zero, expected);
            end
        end
    endtask

    initial begin
        $display("");
        $display("==================  ALU testbench  ==================");

        //---------------------------------------------------------- ADD
        check("add basic",    `ALU_ADD,  32'd7,        32'd5,        32'd12);
        check("add zero",     `ALU_ADD,  32'd0,        32'd0,        32'd0);
        check("add negative", `ALU_ADD,  32'hFFFFFFFF, 32'd1,        32'd0);
        check("add wraps",    `ALU_ADD,  32'hFFFFFFFF, 32'hFFFFFFFF, 32'hFFFFFFFE);
        check("add big",      `ALU_ADD,  32'h7FFFFFFF, 32'd1,        32'h80000000);

        //---------------------------------------------------------- SUB
        check("sub basic",    `ALU_SUB,  32'd10,       32'd3,        32'd7);
        check("sub to zero",  `ALU_SUB,  32'd42,       32'd42,       32'd0);
        check("sub negative", `ALU_SUB,  32'd3,        32'd10,       32'hFFFFFFF9);
        check("sub borrow",   `ALU_SUB,  32'd0,        32'd1,        32'hFFFFFFFF);

        //------------------------------------------------- logical ops
        check("and",          `ALU_AND,  32'hF0F0F0F0, 32'hFF00FF00, 32'hF000F000);
        check("and zero",     `ALU_AND,  32'hFFFFFFFF, 32'h00000000, 32'h00000000);
        check("or",           `ALU_OR,   32'hF0F0F0F0, 32'h0F0F0F0F, 32'hFFFFFFFF);
        check("xor",          `ALU_XOR,  32'hFFFF0000, 32'hFF00FF00, 32'h00FFFF00);
        check("xor self",     `ALU_XOR,  32'hA5A5A5A5, 32'hA5A5A5A5, 32'h00000000);
        check("nor",          `ALU_NOR,  32'h0F0F0F0F, 32'hF0F0F0F0, 32'h00000000);
        check("nor of zeros", `ALU_NOR,  32'h00000000, 32'h00000000, 32'hFFFFFFFF);

        //-------------------------------------------------- SLT signed
        check("slt 1<2",      `ALU_SLT,  32'd1,        32'd2,        32'd1);
        check("slt 2<1",      `ALU_SLT,  32'd2,        32'd1,        32'd0);
        check("slt equal",    `ALU_SLT,  32'd5,        32'd5,        32'd0);
        check("slt -1<1",     `ALU_SLT,  32'hFFFFFFFF, 32'd1,        32'd1);
        check("slt 1<-1",     `ALU_SLT,  32'd1,        32'hFFFFFFFF, 32'd0);
        check("slt -5<-2",    `ALU_SLT,  32'hFFFFFFFB, 32'hFFFFFFFE, 32'd1);

        //------------------------------------------------ SLTU unsigned
        check("sltu 1<2",     `ALU_SLTU, 32'd1,        32'd2,        32'd1);
        check("sltu max",     `ALU_SLTU, 32'hFFFFFFFF, 32'd1,        32'd0);
        check("sltu 1<max",   `ALU_SLTU, 32'd1,        32'hFFFFFFFF, 32'd1);
        check("sltu equal",   `ALU_SLTU, 32'h80000000, 32'h80000000, 32'd0);

        //------------------------------------- shifts:  a = amount, b = value
        check("sll by 4",     `ALU_SLL,  32'd4,        32'h0000000F, 32'h000000F0);
        check("sll by 0",     `ALU_SLL,  32'd0,        32'h12345678, 32'h12345678);
        check("sll by 31",    `ALU_SLL,  32'd31,       32'h00000001, 32'h80000000);
        check("sll drops",    `ALU_SLL,  32'd4,        32'hF0000000, 32'h00000000);

        check("srl by 4",     `ALU_SRL,  32'd4,        32'h000000F0, 32'h0000000F);
        check("srl zero fill",`ALU_SRL,  32'd4,        32'h80000000, 32'h08000000);
        check("srl by 31",    `ALU_SRL,  32'd31,       32'h80000000, 32'h00000001);

        check("sra positive", `ALU_SRA,  32'd4,        32'h000000F0, 32'h0000000F);
        check("sra sign fill",`ALU_SRA,  32'd4,        32'h80000000, 32'hF8000000);
        check("sra all ones", `ALU_SRA,  32'd8,        32'hFFFFFFFF, 32'hFFFFFFFF);
        check("sra by 31",    `ALU_SRA,  32'd31,       32'h80000000, 32'hFFFFFFFF);

        //---------------------------------------------------------- LUI
        check("lui",          `ALU_LUI,  32'd0,        32'h00001234, 32'h12340000);
        check("lui drops hi", `ALU_LUI,  32'd0,        32'hFFFF8000, 32'h80000000);

        //--------------------------------------------------- zero flag
        a = 32'd5; b = 32'd5; ctrl = `ALU_SUB;
        check_zero("zero when equal", 1'b1);
        a = 32'd5; b = 32'd4; ctrl = `ALU_SUB;
        check_zero("clear when diff", 1'b0);

        //------------------------------------------------------ verdict
        $display("");
        $display("  passed %0d   failed %0d", passed, failed);
        if (failed == 0)
            $display("  ALU OK  -  move on to the register file");
        else
            $display("  ALU NOT READY  -  fix the failures above");
        $display("=====================================================");
        $display("");
        $finish;
    end

endmodule
