//==========================================================================
//  control_tb.v  -  self-checking testbench for the control decoder
//
//  Every one of the 27 instructions is checked against Tables 5a and 5b of
//  the proposal. Do not edit this file - if you disagree with a row, the
//  conversation is about the table, not about the test.
//
//  Icarus : iverilog -I rtl -o ctl_tb.out rtl/control.v tb/control_tb.v && vvp ctl_tb.out
//==========================================================================
`timescale 1ns / 1ps
`include "defines.vh"

module control_tb;

    reg  [5:0] opcode, funct;

    wire [1:0] reg_dst;
    wire       alu_src, shamt_src, ext_op;
    wire [3:0] alu_ctrl;
    wire       mem_read, mem_write;
    wire [1:0] branch, jump;
    wire       reg_write;
    wire [1:0] mem_to_reg;

    integer passed = 0;
    integer failed = 0;

    control dut (
        .opcode(opcode), .funct(funct),
        .reg_dst(reg_dst), .alu_src(alu_src), .shamt_src(shamt_src),
        .ext_op(ext_op), .alu_ctrl(alu_ctrl),
        .mem_read(mem_read), .mem_write(mem_write),
        .branch(branch), .jump(jump),
        .reg_write(reg_write), .mem_to_reg(mem_to_reg)
    );

    // one row of the control table
    task row;
        input [8*8:1] name;
        input [5:0]   op, fn;
        input [1:0]   e_dst;
        input         e_alusrc, e_shamt, e_ext;
        input [3:0]   e_alu;
        input         e_mr, e_mw;
        input [1:0]   e_br, e_jmp;
        input         e_rw;
        input [1:0]   e_wb;
        reg           bad;
        begin
            opcode = op; funct = fn;
            #1;
            bad = 1'b0;
            if (reg_write  !== e_rw)     begin bad=1; $display("  FAIL %0s  reg_write  %b want %b", name, reg_write, e_rw); end
            if (mem_write  !== e_mw)     begin bad=1; $display("  FAIL %0s  mem_write  %b want %b", name, mem_write, e_mw); end
            if (mem_read   !== e_mr)     begin bad=1; $display("  FAIL %0s  mem_read   %b want %b", name, mem_read, e_mr); end
            if (alu_ctrl   !== e_alu)    begin bad=1; $display("  FAIL %0s  alu_ctrl   %b want %b", name, alu_ctrl, e_alu); end
            if (alu_src    !== e_alusrc) begin bad=1; $display("  FAIL %0s  alu_src    %b want %b", name, alu_src, e_alusrc); end
            if (shamt_src  !== e_shamt)  begin bad=1; $display("  FAIL %0s  shamt_src  %b want %b", name, shamt_src, e_shamt); end
            if (branch     !== e_br)     begin bad=1; $display("  FAIL %0s  branch     %b want %b", name, branch, e_br); end
            if (jump       !== e_jmp)    begin bad=1; $display("  FAIL %0s  jump       %b want %b", name, jump, e_jmp); end
            // fields that only matter when the instruction writes a register
            if (e_rw && reg_dst    !== e_dst) begin bad=1; $display("  FAIL %0s  reg_dst    %b want %b", name, reg_dst, e_dst); end
            if (e_rw && mem_to_reg !== e_wb)  begin bad=1; $display("  FAIL %0s  mem_to_reg %b want %b", name, mem_to_reg, e_wb); end
            // extend mode only matters when the immediate is used
            if (e_alusrc && ext_op !== e_ext) begin bad=1; $display("  FAIL %0s  ext_op     %b want %b", name, ext_op, e_ext); end

            if (bad) failed = failed + 1; else passed = passed + 1;
        end
    endtask

    initial begin
        $display("");
        $display("============  control decoder testbench  ============");

        //                       opcode      funct        dst       src shamt ext         alu        mr mw  br        jmp        rw  wb
        row("add",  `OP_RTYPE, `FN_ADD,  `DST_RD,  0, 0, `EXT_SIGN, `ALU_ADD,  0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);
        row("addu", `OP_RTYPE, `FN_ADDU, `DST_RD,  0, 0, `EXT_SIGN, `ALU_ADD,  0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);
        row("sub",  `OP_RTYPE, `FN_SUB,  `DST_RD,  0, 0, `EXT_SIGN, `ALU_SUB,  0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);
        row("subu", `OP_RTYPE, `FN_SUBU, `DST_RD,  0, 0, `EXT_SIGN, `ALU_SUB,  0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);
        row("and",  `OP_RTYPE, `FN_AND,  `DST_RD,  0, 0, `EXT_SIGN, `ALU_AND,  0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);
        row("or",   `OP_RTYPE, `FN_OR,   `DST_RD,  0, 0, `EXT_SIGN, `ALU_OR,   0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);
        row("xor",  `OP_RTYPE, `FN_XOR,  `DST_RD,  0, 0, `EXT_SIGN, `ALU_XOR,  0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);
        row("nor",  `OP_RTYPE, `FN_NOR,  `DST_RD,  0, 0, `EXT_SIGN, `ALU_NOR,  0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);
        row("slt",  `OP_RTYPE, `FN_SLT,  `DST_RD,  0, 0, `EXT_SIGN, `ALU_SLT,  0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);
        row("sltu", `OP_RTYPE, `FN_SLTU, `DST_RD,  0, 0, `EXT_SIGN, `ALU_SLTU, 0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);

        row("sll",  `OP_RTYPE, `FN_SLL,  `DST_RD,  0, 1, `EXT_SIGN, `ALU_SLL,  0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);
        row("srl",  `OP_RTYPE, `FN_SRL,  `DST_RD,  0, 1, `EXT_SIGN, `ALU_SRL,  0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);
        row("sra",  `OP_RTYPE, `FN_SRA,  `DST_RD,  0, 1, `EXT_SIGN, `ALU_SRA,  0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);

        row("jr",   `OP_RTYPE, `FN_JR,   `DST_RD,  0, 0, `EXT_SIGN, `ALU_ADD,  0, 0, `BR_NONE, `JMP_JR,   0, `WB_ALU);

        row("addi", `OP_ADDI,  6'bx,     `DST_RT,  1, 0, `EXT_SIGN, `ALU_ADD,  0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);
        row("addiu",`OP_ADDIU, 6'bx,     `DST_RT,  1, 0, `EXT_SIGN, `ALU_ADD,  0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);
        row("slti", `OP_SLTI,  6'bx,     `DST_RT,  1, 0, `EXT_SIGN, `ALU_SLT,  0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);
        row("andi", `OP_ANDI,  6'bx,     `DST_RT,  1, 0, `EXT_ZERO, `ALU_AND,  0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);
        row("ori",  `OP_ORI,   6'bx,     `DST_RT,  1, 0, `EXT_ZERO, `ALU_OR,   0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);
        row("xori", `OP_XORI,  6'bx,     `DST_RT,  1, 0, `EXT_ZERO, `ALU_XOR,  0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);
        row("lui",  `OP_LUI,   6'bx,     `DST_RT,  1, 0, `EXT_ZERO, `ALU_LUI,  0, 0, `BR_NONE, `JMP_NONE, 1, `WB_ALU);

        row("lw",   `OP_LW,    6'bx,     `DST_RT,  1, 0, `EXT_SIGN, `ALU_ADD,  1, 0, `BR_NONE, `JMP_NONE, 1, `WB_MEM);
        row("sw",   `OP_SW,    6'bx,     `DST_RT,  1, 0, `EXT_SIGN, `ALU_ADD,  0, 1, `BR_NONE, `JMP_NONE, 0, `WB_ALU);

        row("beq",  `OP_BEQ,   6'bx,     `DST_RT,  0, 0, `EXT_SIGN, `ALU_SUB,  0, 0, `BR_EQ,   `JMP_NONE, 0, `WB_ALU);
        row("bne",  `OP_BNE,   6'bx,     `DST_RT,  0, 0, `EXT_SIGN, `ALU_SUB,  0, 0, `BR_NE,   `JMP_NONE, 0, `WB_ALU);

        row("j",    `OP_J,     6'bx,     `DST_RT,  0, 0, `EXT_SIGN, `ALU_ADD,  0, 0, `BR_NONE, `JMP_J,    0, `WB_ALU);
        row("jal",  `OP_JAL,   6'bx,     `DST_RA,  0, 0, `EXT_SIGN, `ALU_ADD,  0, 0, `BR_NONE, `JMP_J,    1, `WB_PC4);

        // an opcode we do not implement must behave as a nop
        row("undef", 6'b111111, 6'bx,    `DST_RT,  0, 0, `EXT_SIGN, `ALU_ADD,  0, 0, `BR_NONE, `JMP_NONE, 0, `WB_ALU);

        $display("");
        $display("  passed %0d   failed %0d   (27 instructions + 1 undefined)", passed, failed);
        if (failed == 0)
            $display("  control decoder OK  -  the table is transcribed correctly");
        else
            $display("  control decoder NOT READY  -  check the failures above against Table 5");
        $display("=====================================================");
        $display("");
        $finish;
    end

endmodule
